sudo: false
language: node_js
node_js:
- 5.2 # Latest
- 4.2 # LTS
- 0.1
script:
- npm run lint
- npm run test-ci
cache:
  directories:
  - node_modules
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
- cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/broccoli-sass-tree
    condition: $(node -v | egrep v5.2 | wc -l) = 1
