sudo: false
language: node_js
node_js:
- 5.10 # Latest
- 4.4 # LTS
- 0.10 # Minimum supported
cache:
  directories:
  - $HOME/.npm
before_install: npm -g install npm@latest
script: npm test -- --timeout 15000
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
- cat coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: amercier/broccoli-sass-tree
    condition: $(node -v | egrep v5.2 | wc -l) = 1
