sudo: false
language: node_js
node_js:
- 5.1 # Latest
- 4.2 # LTS
- 0.10
cache:
  directories:
  - node_modules
after_success:
- cat coverage/lcov.info | ./node_modules/.bin/codecov
deploy:
  provider: npm
  email: pro.alexandre.mercier@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    condition: $(node -v | egrep v0.10 | wc -l) = 1
